# fly.toml app configuration file generated for malabon-pickleball-api on 2025-04-18T19:18:52+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'malabon-pickleball-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
